### ISSUE TITLE
Error Connecting to GPS

### ISSUE THREAD

**Issue by ClarkeFL** [sixfab/Sixfab_RPi_3G-4G-LTE_Base_HAT#3]
Hi, I'm currently having an issue connecting to GPS.

I was following your tutorial [Read GNSS/GPS Data with Sixfab Shield/HAT](https://docs.sixfab.com/page/read-gnss-gps-data-with-sixfab-hat) and I was not able to get it to work I then tried running the AT Commands and this is the response I received:

AT+QGPS?
+QGPS: 0 

+QGPS: 0 should be +QGPS: 1 but it is not.

I then run AT+QGPSCFG?
+CME ERROR: 505

I am using Quectel EC25-AUT with the Sixfab 3g/4g/LTE base hat.

Internet connection works fine and is able to browse the internet with a signal quality of 19,99 however I can't get the GPS to work.

Can you please help?

**Comment by hiagofranco** [comment]
Hello ! I have an Sixfab Shield too...
Have you tried the command "AT+QGPS=1"? 
This will set your GPS to ON.

**Comment by ClarkeFL** [comment]
@hiagofranco 

Thank you! yes that has helped!
